### ISSUE TITLE
NoSuchMethodError if running with FindBugs 3.1.0

### ISSUE THREAD

**Issue by iloveeclipse** [mebigfatguy/fb-contrib#116]
Good news: fb-contrib 6.6.1 runs fine on Java 8/9 with the preview of FB 3.1.0.

Bad news: one detector uses BCEL API which is "broken" in latest BCEL 6 snapshot:

`java.lang.NoSuchMethodError: org.apache.bcel.classfile.ParameterAnnotationEntry.getNumAnnotations()I
	at com.mebigfatguy.fbcontrib.detect.OverlyConcreteParameter.buildParameterDefiners(OverlyConcreteParameter.java:448)
	at com.mebigfatguy.fbcontrib.detect.OverlyConcreteParameter.visitCode(OverlyConcreteParameter.java:206)
	at org.apache.bcel.classfile.Code.accept(Code.java:132)
	at edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
	at edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
	at org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
	at edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
	at com.mebigfatguy.fbcontrib.detect.OverlyConcreteParameter.visitClassContext(OverlyConcreteParameter.java:114)
	at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
	at de.tobject.findbugs.builder.FindBugsWorker.runFindBugs(FindBugsWorker.java:321)
	at de.tobject.findbugs.builder.FindBugsWorker.work(FindBugsWorker.java:225)
	at de.tobject.findbugs.actions.FindBugsAction$StartedFromViewJob.runWithProgress(FindBugsAction.java:271)
	at de.tobject.findbugs.FindBugsJob.run(FindBugsJob.java:138)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Comment by mebigfatguy** [comment]
thanks, removed
